// It's probably easiest to derive this file from
// scripts/lib/spreadsheet-mappings.ts in the
// https://github.com/rewiringamerica/api.rewiringamerica.org repo.
// Fields not generated by the API can be omitted.
// TODO: figure out a better way to keep this in sync.
type FieldMetadata = {
  text: string;
  display_name: string;
  required: boolean;
  values?: string[];
};

export type SchemaMetadata = { [index: string]: FieldMetadata };

export const SCHEMA_METADATA: SchemaMetadata = {
  item: {
    text: "the type of technology in the incentive.",
    display_name: "Technology",
    required: true,
    values: [
      "HVAC - Air Source Heat Pump",
      "HVAC - Air to Water Heat Pump",
      "HVAC - Ducted Heat Pump",
      "HVAC - Ductless Heat Pump",
      "Ground Source Heat Pump (GSHP) / Geothermal HP",
      "Heat Pump Water Heater (HPWH)",
      "New Electric Vehicle",
      "Used Electric Vehicle",
      "Electric Vehicle Charger",
      "Rooftop Solar",
      "Battery Storage",
      "Heat Pump Dryers / Clothes Dryer",
      "Induction Cooktop",
      "Weatherization (Insulation and Air Sealing)",
      "Electric Panel",
      "Electric Outdoor Equipment",
      "Smart Thermostat",
      "E-Bike",
      "Electric Thermal Storage/Slab",
      "Evaporative Cooler",
      "Non-Heat Pump Clothes Dryer",
      "Non-Heat Pump Water Heater",
      "Whole House Fan",
      "Other",
    ],
  },
  "short_description.en": {
    display_name: "Program Description",
    text: "a brief summary of the incentive, including the amount (such as dollar value or percentage), Technology, and the most important restrictions, if any. No more than 150 characters.",
    required: true,
  },
  program_status: {
    display_name: "Program Status",
    text: "current availability of the program.",
    required: true,
    values: ["Active", "Expired", "Paused", "Planned", "Other", "Unknown"],
  },
  program_start_raw: {
    display_name: "Program Start",
    text: "if mentioned, a start date for which the program is valid or for which customers must purchase equipment.",
    required: false,
  },
  program_end_raw: {
    display_name: "Program End",
    text: "if mentioned, an end date for which the program is valid or for which customers must purchase equipment.",
    required: false,
  },
  payment_methods: {
    display_name: "Rebate Type",
    text: "the way the incentive is paid to the customer. If the passage indicates the rebate is an instant rebate or applied at time of purchase, it is Point of Sale rebate. If it mentions receiving a check or mailing in an application after purchase, it is Rebate (post purchase). If it says it will apply it as a credit on the utility bill, it is Account Credit. And if it mentions tax credits, it is a Tax Credit.",
    required: true,
    values: [
      "Rebate (Post Purchase)",
      "Point of Sale Rebate",
      "Account Credit",
      "Tax Credit",
      "Assistance Program",
      "Bonus",
      "Multiple",
      "Other",
      "Unknown",
      "Financing",
    ],
  },
  rebate_value: {
    display_name: "Rebate Value",
    text: "A free-text version of the value of the rebate (e.g. $2000, $500 per ton). If the rebate has both a percentage cap (e.g. 25% of costs) and a dollar maximum (up to $3,000), include both.",
    required: true,
  },
  "amount.type": {
    display_name: "Amount Type",
    text: "The financial structure of the rebate.",
    required: true,
    values: ["Dollar Per Unit", "Percent", "Dollar Amount"],
  },
  "amount.number": {
    display_name: "Amount Number",
    text: 'Only the number of the Rebate Value. If the Rebate Value is "$2,500", it would be 2500, and if the Rebate Value is "$100 / ton", it would be 100. Give percentages as a decimal; e.g. 25% is 0.25. If the incentive has both a percentage and a dollar maximum, give the percentage.',
    required: true,
  },
  "amount.unit": {
    display_name: "Amount Unit",
    text: "if the Amount type is amount per unit, then this will be the corresponding unit, such as ton, sq ft, or kilowatt",
    required: false,
  },
  "amount.minimum": {
    display_name: "Amount Minimum",
    text: "the minimum amount associated with the incentive, if any. Do not include commas or units like $ or % in your answer.",
    required: false,
  },
  "amount.maximum": {
    display_name: "Amount Maximum",
    text: "the maximum amount associated with the incentive, if any. For example, if the incentive reads '50% up to $50', then this would be 50. Do not include commas or units like $ or % in your answer.",
    required: false,
  },
  bonus_description: {
    display_name: "Bonus Description",
    text: 'description of the bonus mentioned in the incentive, if any. Bonuses are additional offers directly tied to an incentive and will likely use the words "bonus" or "additional".',
    required: false,
  },
  equipment_standards_restrictions: {
    display_name: "Equipment Standards Restrictions",
    text: "specifications for the efficiency of the appliance, if any",
    required: false,
  },
  equipment_capacity_restrictions: {
    display_name: "Equipment Capacity Restrictions",
    text: "requirements for the size or capacity of the unit, if any",
    required: false,
  },
  contractor_restrictions: {
    display_name: "Contractor Restrictions",
    text: "requirements for who the unit is installed by, such as whether a licensed contractor is required",
    required: false,
  },
  income_restrictions: {
    display_name: "Income Restrictions",
    text: "if the customer has any restrictions on their income in order to claim the rebate",
    required: false,
  },
  filing_status: {
    display_name: "Tax-Filing Status",
    text: "if there are any restrictions on the customer's tax-filing status (e.g. single or joint filing), list them here",
    required: false,
    values: [
      "Head of Household",
      "Joint",
      "Married, Filing Separately",
      "Single",
      "Qualifying Widower with Dependent Child",
    ],
  },
  other_restrictions: {
    display_name: "Other Restrictions",
    text: "for other important restrictions not covered by the above",
    required: false,
  },
  stacking_details: {
    display_name: "Stacking Details",
    text: "for any restrictions on how rebates can be combined. For example, if there is a dollar limit across multiple incentives, that would go here. Note that limits for a single incentive should be listed in Other Restrictions.",
    required: false,
  },
  financing_details: {
    display_name: "Financing Details",
    text: "if information is given related to how to finance the project, include it here",
    required: false,
  },
};
